# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CVDL_UI_MAC.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1680, 916)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)

        # 載入照片的主要界面
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 圖片加載相關操作的組件
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 10, 200, 460))
        self.groupBox.setObjectName("groupBox")
        self.LoadFolder = QtWidgets.QPushButton(self.groupBox)
        self.LoadFolder.setGeometry(QtCore.QRect(40, 40, 120, 40))
        self.LoadFolder.setObjectName("LoadFolder")
        self.LoadFolder.setStyleSheet("background-color: lightblue;")
        
        self.LoadImgL = QtWidgets.QPushButton(self.groupBox)
        self.LoadImgL.setGeometry(QtCore.QRect(40, 100, 120, 40))
        self.LoadImgL.setObjectName("LoadImgL")
        self.LoadImgL.setStyleSheet("background-color: lightgreen;")
        
        self.LoadImgR = QtWidgets.QPushButton(self.groupBox)
        self.LoadImgR.setGeometry(QtCore.QRect(40, 160, 120, 40))
        self.LoadImgR.setObjectName("LoadImgR")
        self.LoadImgR.setStyleSheet("background-color: lightpink;")

        # 相機標定相關操作的組件
        self.groupBox_Q1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q1.setGeometry(QtCore.QRect(300, 10, 250, 460))
        self.groupBox_Q1.setObjectName("groupBox_Q1")
        
        self.FindCorners = QtWidgets.QPushButton(self.groupBox_Q1)
        self.FindCorners.setGeometry(QtCore.QRect(45, 40, 160, 40))
        self.FindCorners.setObjectName("FindCorners")
        self.FindCorners.setStyleSheet("background-color: lightyellow;")
        
        self.FindDistortion = QtWidgets.QPushButton(self.groupBox_Q1)
        self.FindDistortion.setGeometry(QtCore.QRect(45, 340, 160, 40))
        self.FindDistortion.setObjectName("FindDistortion")
        self.FindDistortion.setStyleSheet("background-color: lightcoral;")
        
        self.ShowResult = QtWidgets.QPushButton(self.groupBox_Q1)
        self.ShowResult.setGeometry(QtCore.QRect(45, 400, 160, 40))
        self.ShowResult.setObjectName("ShowResult")
        self.ShowResult.setStyleSheet("background-color: lightgrey;")

        # 相機外部參數的查找組件
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_Q1)
        self.groupBox_7.setGeometry(QtCore.QRect(25, 160, 200, 160))
        self.groupBox_7.setObjectName("groupBox_7")
        
        self.comboBox = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox.setGeometry(QtCore.QRect(50, 50, 100, 22))
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")

        self.FindExtrinsic = QtWidgets.QPushButton(self.groupBox_7)
        self.FindExtrinsic.setGeometry(QtCore.QRect(30, 90, 140, 40))
        self.FindExtrinsic.setObjectName("FindExtrinsic")
        self.FindExtrinsic.setStyleSheet("background-color: lavender;")
        
        self.FindIntrinsic = QtWidgets.QPushButton(self.groupBox_Q1)
        self.FindIntrinsic.setGeometry(QtCore.QRect(45, 100, 160, 40))
        self.FindIntrinsic.setObjectName("FindIntrinsic")
        self.FindIntrinsic.setStyleSheet("background-color: thistle;")

        # 增強現實相關操作的組件
        self.groupBox_Q2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q2.setGeometry(QtCore.QRect(600, 10, 300, 460))
        self.groupBox_Q2.setObjectName("groupBox_Q2")
        
        self.ShowWordsOnBoard = QtWidgets.QPushButton(self.groupBox_Q2)
        self.ShowWordsOnBoard.setGeometry(QtCore.QRect(50, 350, 200, 40))
        self.ShowWordsOnBoard.setObjectName("ShowWordsOnBoard")
        self.ShowWordsOnBoard.setStyleSheet("background-color: lightcyan;")
        
        self.ShowWordsVertically = QtWidgets.QPushButton(self.groupBox_Q2)
        self.ShowWordsVertically.setGeometry(QtCore.QRect(50, 400, 200, 40))
        self.ShowWordsVertically.setObjectName("ShowWordsVertically")
        self.ShowWordsVertically.setStyleSheet("background-color: moccasin;")
        
        self.GraphLabel = QtWidgets.QLabel(self.groupBox_Q2)
        self.GraphLabel.setGeometry(QtCore.QRect(25, 40, 250, 250))
        self.GraphLabel.setStyleSheet("background-color: white;")
        self.GraphLabel.setText("")
        self.GraphLabel.setObjectName("GraphLabel")
        
        self.InputText = QtWidgets.QTextEdit(self.groupBox_Q2)
        self.InputText.setGeometry(QtCore.QRect(25, 300, 250, 40))
        self.InputText.setObjectName("InputText")

        # 立體視差圖相關操作的組件
        self.groupBox_Q3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q3.setGeometry(QtCore.QRect(950, 10, 220, 460))
        self.groupBox_Q3.setObjectName("groupBox_Q3")
        
        self.StereoDisparityMap = QtWidgets.QPushButton(self.groupBox_Q3)
        self.StereoDisparityMap.setGeometry(QtCore.QRect(10, 200, 200, 40))
        self.StereoDisparityMap.setObjectName("StereoDisparityMap")
        self.StereoDisparityMap.setStyleSheet("background-color: peachpuff;")

        # 提示信息的顯示區域
        self.HintLabel = QtWidgets.QLabel(self.centralwidget)
        self.HintLabel.setGeometry(QtCore.QRect(50, 620, 300, 80))
        self.HintLabel.setText("")
        self.HintLabel.setObjectName("HintLabel")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1680, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        # SIFT相關操作的組件
        self.groupBox_Q4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q4.setGeometry(QtCore.QRect(1250, 10, 300, 460))
        self.groupBox_Q4.setObjectName("groupBox_Q4")
        
        self.LoadImgOne = QtWidgets.QPushButton(self.groupBox_Q4)
        self.LoadImgOne.setGeometry(QtCore.QRect(50, 40, 200, 40))
        self.LoadImgOne.setObjectName("LoadImgOne")
        self.LoadImgOne.setStyleSheet("background-color: lightgoldenrodyellow;")
        
        self.LoadImgTwo = QtWidgets.QPushButton(self.groupBox_Q4)
        self.LoadImgTwo.setGeometry(QtCore.QRect(50, 100, 200, 40))
        self.LoadImgTwo.setObjectName("LoadImgTwo")
        self.LoadImgTwo.setStyleSheet("background-color: lightsteelblue;")
        
        self.Keypoints = QtWidgets.QPushButton(self.groupBox_Q4)
        self.Keypoints.setGeometry(QtCore.QRect(50, 160, 200, 40))
        self.Keypoints.setObjectName("Keypoints")
        self.Keypoints.setStyleSheet("background-color: lightcoral;")
        
        self.MatchedKeypoints = QtWidgets.QPushButton(self.groupBox_Q4)
        self.MatchedKeypoints.setGeometry(QtCore.QRect(50, 220, 200, 40))
        self.MatchedKeypoints.setObjectName("MatchedKeypoints")
        self.MatchedKeypoints.setStyleSheet("background-color: plum;")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Load"))
        self.LoadFolder.setText(_translate("MainWindow", "Load Folder"))
        self.LoadImgL.setText(_translate("MainWindow", "Load Image_L"))
        self.LoadImgR.setText(_translate("MainWindow", "Load Image_R"))
        self.groupBox_Q1.setTitle(_translate("MainWindow", "1. Camera Calibration"))
        self.FindCorners.setText(_translate("MainWindow", "1.1 Find Corners"))
        self.FindDistortion.setText(_translate("MainWindow", "1.4 Find Distortion"))
        self.ShowResult.setText(_translate("MainWindow", "Show Result"))
        self.groupBox_7.setTitle(_translate("MainWindow", "1.3 Find Extrinsic"))
        self.FindExtrinsic.setText(_translate("MainWindow", "Find Extrinsic"))
        self.FindIntrinsic.setText(_translate("MainWindow", "1.2 Find Intrinsic"))
        self.groupBox_Q2.setTitle(_translate("MainWindow", "2. Augmented Reality"))
        self.ShowWordsOnBoard.setText(_translate("MainWindow", "Show Words on Board"))
        self.ShowWordsVertically.setText(_translate("MainWindow", "Show Words Vertically"))
        self.groupBox_Q3.setTitle(_translate("MainWindow", "3. Stereo Disparity Map"))
        self.StereoDisparityMap.setText(_translate("MainWindow", "3.1 Stereo Disparity Map"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.groupBox_Q4.setTitle(_translate("MainWindow", "4. SIFT"))
        self.LoadImgOne.setText(_translate("MainWindow", "Load Image 1"))
        self.LoadImgTwo.setText(_translate("MainWindow", "Load Image 2"))
        self.Keypoints.setText(_translate("MainWindow", "4.1 Keypoints"))
        self.MatchedKeypoints.setText(_translate("MainWindow", "4.2 Matched Keypoints"))
